### ISSUE TITLE
Compatibility with casalite ?

### ISSUE THREAD

**Issue by JulienNGirard** [aroffringa/dysco#10]
Some of us were trying to read LOFAR Dysco compressed MS with classic CASA tools (casabrowser, casaplotms, etc). We are using casalite-5.1.1 and have dysco 1.2 installed and compiled. 

First, when opening or plotting a MS we got a path issue:
`julien.girard@nancep5:/cep/lofar/dysco/lib$ casaplotms 
--> CrashReporter initialized.
2020-09-25 15:25:29	INFO	PlotMS::params_changed	Updating: REDRAW, MSDATA, CACHE, AXES, CANVAS, DISPLAY, PAGEHEADER, ITERATION, LOG, PLOTMS_OPTIONS.
2020-09-25 15:25:29	INFO	PlotMS::load_cache	Clearing the existing plotms cache.
2020-09-25 15:25:50	INFO	PlotMS::params_changed	Updating: REDRAW, MSDATA.
2020-09-25 15:25:50	INFO	PlotMS::load_cache	Clearing the existing plotms cache.
2020-09-25 15:25:50	INFO	PlotMS::load_cache	START     Current memory usage: 6391.5 kilobytes.
Could not update cache: Shared library dyscostman not found in CASACORE_LDPATH or (DY)LD_LIBRARY_PATH
/opt/casalite-5.1.1/lib/libcasa_dyscostman.so.2737.152.136: cannot open shared object file: No such file or directory
/opt/casalite-5.1.1/lib/libcasa_dyscostman.so: cannot open shared object file: No such file or directory
/opt/casalite-5.1.1/lib/libdyscostman.so.2737.152.136: cannot open shared object file: No such file or directory
/opt/casalite-5.1.1/lib/libdyscostman.so: cannot open shared object file: No such file or directory
libcasa_dyscostman.so.2737.152.136: cannot open shared object file: No such file or directory
libcasa_dyscostman.so: cannot open shared object file: No such file or directory
libdyscostman.so.2737.152.136: cannot open shared object file: No such file or directory
libdyscostman.so: cannot open shared object file: No such file or directory

2020-09-25 15:25:50	INFO	PlotMS::load_cache	Clearing the existing plotms cache.
2020-09-25 15:25:50	INFO	PlotMS::load_cache	Clearing the existing plotms cache.
`
We can see that it is trying to find libcasa_dyscostman.so in /opt/casalite-5.1.1/ lib dir, whereas it is installed somewhere else (in /cep/lofar/dysco/lib in our case).

1) I first tried to populate CASACORE_LDPATH and LD_LIBRARY_PATH with the correct path but got the same message again.

2) by inspecting casaplotms (which is a PERL script itself), I could see that the CASALD_LIBRARY_PATH was in fact the right one to use, so I used it before running Casaplotms:
`export CASALD_LIBRARY_PATH=/cep/lofar/dysco/lib`

So, CASA no longer complained about missing lib, but crashed anyway when I tried to plot:

`julien.girard@nancep5:/opt/casalite/bin$ ./casaplotms 
--> CrashReporter initialized.
2020-09-25 15:29:00	INFO	PlotMS::params_changed	Updating: REDRAW, MSDATA, CACHE, AXES, CANVAS, DISPLAY, PAGEHEADER, ITERATION, LOG, PLOTMS_OPTIONS.
2020-09-25 15:29:00	INFO	PlotMS::load_cache	Clearing the existing plotms cache.
2020-09-25 15:29:20	INFO	PlotMS::params_changed	Updating: REDRAW, MSDATA.
2020-09-25 15:29:20	INFO	PlotMS::load_cache	Clearing the existing plotms cache.
2020-09-25 15:29:20	INFO	PlotMS::load_cache	START     Current memory usage: 6383.69 kilobytes.
--------------------------------------------------------------
CASA has crashed...
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
A crash report is being generated and submitted. The report
will contain information about CASA's environment when the
crash occurred (e.g. CASA log, call stack, CPU information).
This should not take too long...
--------------------------------------------------------------
`

So:

1) Can CASA tools opens Dyscoed MS?
2) Shall I use a specific build of Dysco? of Casa?
3) shall I set CASA on fire? :)
4) should I "decompress" a MS before trying to use it with CASA? (does it make sense? if so, how?)
5) maybe I am using it wrong

thanks !

Julien & Lilia

**Comment by aroffringa** [comment]
Hi Julien,

To answer your questions one by one:
1. Yes, CASA tools can theoretically open Dyscoed MSes "transparently". However, it requires that Casa and Dysco are build with the same version (well, binary compatible) of casacore. This is unlikely to be the case in practice, and basically means you have to compile Casa yourself to achieve this. In a distant past I've been able to achieve this and use Casa on Dyscoed sets, but it's a bit of a work. I don't know what Casalite is, but I assume it's a trimmed down version of Casa? In that the same holds for Casalite.
2. The exact releases shouldn't matter -- it's really about the binary compatibility of the casacore 
3. While a good bonfire is always nice, I think Casa has its uses, so if it fits it in your use-cases and has added value over other tools, I don't see a reason to change.
4. That is the easiest way indeed of using Casa on compressed data, and is also what LOFAR support advises in their description of Dysco. There's the double penalty of a) first having an extra task to run; and b) to require quite a bit more space, but if that's not an issue it's the easiest approach.
4b. For LOFAR data, one can use DPPP to decompress a MS -- see its manual.
5. Apart from the points above, I don't think so.

**Comment by JulienNGirard** [comment]
thanks for the quick answer !

**Comment by aroffringa** [comment]
(See also https://github.com/casacore/casacore/issues/876 )
