### ISSUE TITLE
dysco not working in kernsuite

### ISSUE THREAD

**Issue by phiadaarr** [aroffringa/dysco#11]
When I do:
```
from casacore.tables import table
table("name.ms")
```
where `name.ms` is a dysco-compressed measurement set, I get the error:
```
  File "/usr/lib/python3/dist-packages/casacore/tables/table.py", line 373, in __init__
    Table.__init__(self, tabname, lockopt, opt)
RuntimeError: Table DataManager error: Data Manager class DyscoStMan is not registered
  Check (DY)LD_LIBRARY_PATH matches the libraries used during the build of DyscoStMan
```

My docker file looks like this:
```
FROM kernsuite/base:latest
ENV DEBIAN_FRONTEND noninteractive
RUN docker-apt-install dysco dysco-dev python3-casacore
```

I have discussed this a little with @gijzelaerr already here: https://github.com/kernsuite/packaging/issues/234

Do you know what is going on, @aroffringa?

**Comment by aroffringa** [comment]
There's probably something wrong with paths set, or the casacore version (or other dependency) used to compile dysco vs the one used for python3-casacore don't match.
