### ISSUE TITLE
Dysco + casaplotms: Could not update cache: Shared library dyscostman not found

### ISSUE THREAD

**Issue by AlexKurek** [aroffringa/dysco#12]
Im trying to use casaplotms from latest CASA `casa-release-5.7.2-4.el7` as show in CoockBook:
https://support.astron.nl/LOFARImagingCookbook/tutorial.html#flagging-averaging-and-demixing
and Im getting:

> Could not update cache: Shared library dyscostman not found in CASACORE_LDPATH or (DY)LD_LIBRARY_PATH
> /usr/local/CASA/casa-release-5.7.2-4.el7/lib/libcasa_dyscostman.so.3379.154.232: cannot open shared object file: No such file or directory
> /usr/local/CASA/casa-release-5.7.2-4.el7/lib/libcasa_dyscostman.so: cannot open shared object file: No such file or directory
> /usr/local/CASA/casa-release-5.7.2-4.el7/lib/libdyscostman.so.3379.154.232: cannot open shared object file: No such file or directory
> /usr/local/CASA/casa-release-5.7.2-4.el7/lib/libdyscostman.so: cannot open shared object file: No such file or directory
> libcasa_dyscostman.so.3379.154.232: cannot open shared object file: No such file or directory
> libcasa_dyscostman.so: cannot open shared object file: No such file or directory
> libdyscostman.so.3379.154.232: cannot open shared object file: No such file or directory
> libdyscostman.so: cannot open shared object file: No such file or directory

This is what I have in Dysco's lib/ dir:
`libdyscostman.so  libdyscostman.so.0`
And it is in `LD_LIBRARY_PATH`. Im guessing this is some version mismatch? Is there a way to use casaplotms presently?

**Comment by tammojan** [comment]
A workaround would be to decompress the measurement set so that dysco is not needed to read it. Recompiling dysco against the exact casacore used in casa-release-5.7.2-4.el7 should also be possible, though not easy.

**Comment by aroffringa** [comment]
https://github.com/casacore/casacore/issues/876 would solve this issue. Should we revamp that discussion once more, @tammojan ?

**Comment by AlexKurek** [comment]
How can I decompress the MS? As far as I understand `dscompress `can only compress the data?

**Comment by tammojan** [comment]
An executable `decompress` should be built as part of dysco, but looking at the CMakeListst.txt it doesn't seem to be installed. So it may be available in your build directory. Also, you could use DPPP to decompress the data.

**Comment by AlexKurek** [comment]
Thats right, it was there. I copied it to Dysco's bin/ and now Im getting:

> Current data manager of DATA column: StandardStMan
> Current data manager of WEIGHT_SPECTRUM column: DyscoStMan
> Renaming old WEIGHT_SPECTRUM column...
> Copying values for WEIGHT_SPECTRUM ...
> Removing old column...
> Reordering ms...
> Finished.
> terminate called after throwing an instance of 'casa::AipsError'
>   what():  RegularFile: /storage/kurek/extracted/P311+61_NGC6946.dysco.sub.shift.avg.weights.ms.archive0.calibratedtemp/STATE/table.dat does not exist and cannot be created
> Aborted

After I repeated the command, there were no errors and it all worked.
