### ISSUE TITLE
Compilation crashes

### ISSUE THREAD

**Issue by AlexKurek** [aroffringa/dysco#18]
Im getting the following error:

[ 57%] Building CXX object CMakeFiles/dyscostman-object.dir/rowtimeblockencoder.cpp.o
In file included from /opt/dysco/dysco/dyscostman.cpp:1:
/opt/dysco/dysco/dyscostman.h:389:16: error: 'mutex' in namespace 'std' does not name a type
  389 |   mutable std::mutex _mutex;
      |                ^~~~~
/opt/dysco/dysco/dyscostman.h:15:1: note: 'std::mutex' is defined in header '<mutex>'; did you forget to '#include <mutex>'?
   14 | #include "uvector.h"
  +++ |+#include <mutex>
   15 | 
/opt/dysco/dysco/dyscostman.h: In member function 'uint64_t dyscostman::DyscoStMan::nBlocksInFile() const':
/opt/dysco/dysco/dyscostman.h:237:10: error: 'lock_guard' is not a member of 'std'
  237 |     std::lock_guard<std::mutex> lock(_mutex);
      |          ^~~~~~~~~~
/opt/dysco/dysco/dyscostman.h:237:10: note: 'std::lock_guard' is defined in header '<mutex>'; did you forget to '#include <mutex>'?
/opt/dysco/dysco/dyscostman.h:237:26: error: 'mutex' is not a member of 'std'
  237 |     std::lock_guard<std::mutex> lock(_mutex);
      |                          ^~~~~
/opt/dysco/dysco/dyscostman.h:237:26: note: 'std::mutex' is defined in header '<mutex>'; did you forget to '#include <mutex>'?
/opt/dysco/dysco/dyscostman.h:237:38: error: '_mutex' was not declared in this scope
  237 |     std::lock_guard<std::mutex> lock(_mutex);
      |                                      ^~~~~~
/opt/dysco/dysco/dyscostman.h:237:33: error: 'lock' was not declared in this scope; did you mean 'lockf'?
  237 |     std::lock_guard<std::mutex> lock(_mutex);
      |                                 ^~~~
      |                                 lockf
/opt/dysco/dysco/dyscostman.cpp: In member function 'virtual void dyscostman::DyscoStMan::prepare()':
/opt/dysco/dysco/dyscostman.cpp:325:36: error: '_mutex' was not declared in this scope
  325 |   std::lock_guard<std::mutex> lock(_mutex);
      |                                    ^~~~~~
/opt/dysco/dysco/dyscostman.cpp: In member function 'void dyscostman::DyscoStMan::readCompressedData(size_t, const dyscostman::DyscoStManColumn*, unsigned char*, size_t)':
/opt/dysco/dysco/dyscostman.cpp:389:36: error: '_mutex' was not declared in this scope
  389 |   std::lock_guard<std::mutex> lock(_mutex);
      |                                    ^~~~~~
/opt/dysco/dysco/dyscostman.cpp: In member function 'void dyscostman::DyscoStMan::writeCompressedData(size_t, const dyscostman::DyscoStManColumn*, const unsigned char*, size_t)':
/opt/dysco/dysco/dyscostman.cpp:408:36: error: '_mutex' was not declared in this scope
  408 |   std::lock_guard<std::mutex> lock(_mutex);
      |                                    ^~~~~~
CMakeFiles/dyscostman-object.dir/build.make:94: recipe for target 'CMakeFiles/dyscostman-object.dir/dyscostman.cpp.o' failed
make[2]: *** [CMakeFiles/dyscostman-object.dir/dyscostman.cpp.o] Error 1

Im using casacore 2.4.1, since this is the latest version compatible with Prefactor.

**Comment by aroffringa** [comment]
Thanks, should be fixed in #19.
