### ISSUE TITLE
dscompress failure

### ISSUE THREAD

**Issue by agwilber** [aroffringa/dysco#28]
Hi there, trying to decompress a LOFAR data set and I got the following error:

dscompress -afnormalization -truncgaus 2.5 -data-bit-rate 4 -weight-bit-rate 12 -column DATA -column WEIGHT_SPECTRUM P10Hetdex_Abell1314.dysco.sub.shift.avg.weights.ms.archive.calibrated.ms
	bits per data val = 4
	bits per weight = 12
	distribution = Truncated Gaussian with sigma=2.5
	normalization = AF

Opening ms...
Replacing flagged values by NaNs...
Time taken: 00:01:13.449639
Validating MS ordering...
Time taken: 00:00:00.086118
Current data manager of DATA column: DyscoStMan
Current data manager of WEIGHT_SPECTRUM column: StandardStMan
Renaming old WEIGHT_SPECTRUM column...
Constructing new column 'DATA'...
Querying storage manager...
Constructing storage manager...
Adding column...
terminate called after throwing an instance of 'casacore::TableInvOper'
  what():  Invalid Table operation: TableDesc::add; columns not disjoint
Aborted (core dumped)

**Comment by aroffringa** [comment]
Hi @agwilber , the `dscompress` tool is for compressing a measurement set instead of decompressing, and is mainly aimed at experimentation (see https://github.com/aroffringa/dysco/wiki#dscompress ). For decompression of LOFAR data, the DP3 tool is the recommended method.

**Comment by AlexKurek** [comment]
Im getting similar error when trying to decompress using 'decompress':
`$ decompress 42_NGC4449.dysco.sub.shift.avg.weights.ms.archive0.calibrated     `                                                                                 

```
terminate called after throwing an instance of 'casacore::TableNoFile'
  what():  Table /storage/akurek/extractPy/NGC4449_3pola_timeAv_1_REIMAGED_unDysco/42_NGC4449.dysco.sub.shift.avg.weights.ms.archive0.calibrated does not exist
Aborted (core dumped)
```

**Comment by physicistsam** [comment]
@aroffringa Thanks for the discussion. Could you please let me know how exactly to decompress using DP3 tool, I am unable to locate any refence command regarding that.
