### ISSUE TITLE
CMake configuration

### ISSUE THREAD

**Issue by gijzelaerr** [aroffringa/dysco#3]
libdyscostman is missing SO version in name and it is linked against libgslcblas while it doesnt use it.

dpkg-shlibdeps: warning: can't extract name and version from library name 'libdyscostman.so'
dpkg-shlibdeps: warning: can't extract name and version from library name 'libdyscostman.so'
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/dysco/usr/lib/libdyscostman.so was not linked against libgslcblas.so.0 (it uses none of the library's symbols)

**Comment by aroffringa** [comment]
I've pushed fixes, could you check if trunk is OK now? Do you want me to release a new version?

**Comment by gijzelaerr** [comment]
thanks. Everything looks good now. No new release required.

**Comment by gijzelaerr** [comment]
ah maybe just do a new 1.0.1 release or something, i need to update the package anyway so then everything is nice and clean for KERN-2.

**Comment by aroffringa** [comment]
Ok, v1.0.1 is released.

**Comment by sabourke** [comment]
I do need to link against gslcblas (or another cblas) for the executables (dscompress, decompress). Also decompress doesn't get installed. Is that intentional? I'm on CentOS6.
